# Generated by Django 5.0.4 on 2024-04-26 19:59

import django.core.validators
import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255, verbose_name='Название курса')),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(verbose_name='Описание курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер урока')),
                ('title', models.CharField(max_length=255, verbose_name='Название урока')),
                ('description', models.TextField(verbose_name='Короткое описание')),
                ('lesson', django_quill.fields.QuillField(default='Текст', verbose_name='Занятие')),
                ('presentation_file', models.FileField(blank=True, default=None, upload_to='pptxfiles/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'png', 'xlsx', 'xls'], 'Unsupported file format')], verbose_name='Файл занятия')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.courses')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
