# Generated by Django 5.0.4 on 2024-04-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options_rename_task_task_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Lesson',
        ),
    ]
