# Generated by Django 5.0.4 on 2024-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.PositiveBigIntegerField(verbose_name='Номер урока'),
        ),
    ]
