# Generated by Django 5.0.4 on 2024-04-19 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_lesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер урока'),
        ),
    ]
