# Generated by Django 5.0.4 on 2024-04-27 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_lesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='presentation_file',
            field=models.FileField(blank=True, default=None, upload_to='pptxfiles/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xlsx', 'xls'], 'Unsupported file format')], verbose_name='Файл занятия'),
        ),
    ]
