# Generated by Django 5.0.4 on 2024-05-03 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_lesson_presentation_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('password', models.CharField(max_length=100, verbose_name='Пароль к уроку')),
                ('is_active', models.BooleanField(default=False, verbose_name='Доступно')),
                ('lesson', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.lesson')),
            ],
            options={
                'verbose_name': 'Доступный урок',
                'verbose_name_plural': 'Доступные уроки',
            },
        ),
    ]
