# Generated by Django 5.0.4 on 2024-04-19 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_lesson_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255, verbose_name='Название курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='courseId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.courses'),
            preserve_default=False,
        ),
    ]
