# Generated by Django 5.0.4 on 2024-04-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_courses_lesson_courseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='courseId',
        ),
    ]
