# Generated by Django 5.0.4 on 2024-04-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
