# Generated by Django 5.0.4 on 2024-05-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_availablelessons_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablelessons',
            name='link',
            field=models.CharField(max_length=250, null=True, verbose_name='Ссылка'),
        ),
    ]
