# Generated by Django 5.0.4 on 2024-04-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_lesson_courseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание курса'),
            preserve_default=False,
        ),
    ]
