# Generated by Django 5.0.4 on 2024-05-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_availablelessons_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablelessons',
            name='link',
        ),
    ]
