# Generated by Django 5.0.4 on 2024-05-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_availablelessons_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablelessons',
            name='link',
            field=models.URLField(max_length=250, null=True, verbose_name='Ссылка'),
        ),
    ]
