# Generated by Django 5.0.4 on 2024-04-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_lesson_courseid_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='presentation_file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
