# Generated by Django 5.0.4 on 2024-04-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_lesson_presentation_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='presentation_file',
        ),
    ]
