# Generated by Django 5.0.4 on 2024-05-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_availablelessons_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablelessons',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Доступность без пароля'),
        ),
    ]
