# Generated by Django 5.0.4 on 2024-04-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_lesson_presentation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='presentation_file',
            field=models.FileField(default=None, upload_to='pptxfiles/'),
        ),
    ]
