# Generated by Django 5.0.4 on 2024-05-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_commentsonlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsonlesson',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
