# Generated by Django 5.0.6 on 2024-05-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Lesson',
            new_name='lesson',
        ),
    ]
